### ISSUE TITLE
请问如何复现表格结果呢

### ISSUE THREAD

**Issue by 2catycm** [easezyc/Multitask-Recommendation-Library#11]
我试了很多参数，效果都远远不如表格中的，比如NL数据集两个任务auc只跑到0.
74和0.
69。
其中第二个任务差的特别远，没有见到过0.
8。
请问有可能是什么原因呢？能不能问下得到比如NL数据集表格中metaheuc的效果，batchsize和lr等参数怎么设置呢

**Comment by easezyc** [comment]
我所有方法在我这里是gridsearch学习率，batchsize都是固定的，就是列的参数。这个结果也有可能是pytorch版本不同导致。在我本地跑出来没啥问题，都是重复实验取均值。

**Comment by 2catycm** [comment]
好的，用列的参数现在跑没啥问题了
